.TH "kaco2pvo.powerReading" 3 "Tue Jan 20 2015" "kaco2pv" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kaco2pvo.powerReading \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtimeOfReading\fP (self)"
.br
.ti -1c
.RI "def \fBgeneratedPower\fP (self)"
.br
.ti -1c
.RI "def \fBtemperature\fP (self)"
.br
.ti -1c
.RI "def \fBgeneratedVoltage\fP (self)"
.br
.ti -1c
.RI "def \fBgeneratedCurrent\fP (self)"
.br
.ti -1c
.RI "def \fB__init__\fP (self, \fBtimeOfReading\fP, dailyRunTime, operatingState, generatorVoltage, generatorCurrent, generatorPower, lineVoltage, lineCurrentFeedIn, powerFeedIn, unitTemperature)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
class containing power reading data 
.fi
.PP
 
.PP
Definition at line 187 of file kaco2pvo\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def kaco2pvo\&.powerReading\&.__init__ ( self,  timeOfReading,  dailyRunTime,  operatingState,  generatorVoltage,  generatorCurrent,  generatorPower,  lineVoltage,  lineCurrentFeedIn,  powerFeedIn,  unitTemperature)"

.PP
.nf
class initialiser 
.fi
.PP
 
.PP
Definition at line 224 of file kaco2pvo\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def kaco2pvo\&.powerReading\&.generatedCurrent ( self)"

.PP
.nf
returns generated current 
.fi
.PP
 
.PP
Definition at line 216 of file kaco2pvo\&.py\&.
.SS "def kaco2pvo\&.powerReading\&.generatedPower ( self)"

.PP
.nf
returns generated power 
.fi
.PP
 
.PP
Definition at line 204 of file kaco2pvo\&.py\&.
.SS "def kaco2pvo\&.powerReading\&.generatedVoltage ( self)"

.PP
.nf
returns generated voltage 
.fi
.PP
 
.PP
Definition at line 212 of file kaco2pvo\&.py\&.
.SS "def kaco2pvo\&.powerReading\&.temperature ( self)"

.PP
.nf
returns temperature 
.fi
.PP
 
.PP
Definition at line 208 of file kaco2pvo\&.py\&.
.SS "def kaco2pvo\&.powerReading\&.timeOfReading ( self)"

.PP
.nf
returns time of reading 
.fi
.PP
 
.PP
Definition at line 200 of file kaco2pvo\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kaco2pv from the source code\&.
